#!/bin/bash
set -eou pipefail

go build distribution.go
./distribution 500000 5 6 > dist.56
./distribution 500000 5 5 > dist.55

gnuplot << ENDCMDS
set title "500,000 Games that end in 5/6"
set xlabel "Length of game in rolls"
set ylabel "Proportion of all games"
set grid
set xtics 50
set ytics .005
set term png
set out '500.png'
plot 'dist.55' using 1:3 with point pointtype 7 pointsize .5 title "5:5 game", \
'dist.56' using 1:3 with point pointtype 7 pointsize .5 title "5:6 game", 
ENDCMDS

